[build]
command = "NG_APP_API_URL=$NG_APP_API_URL npx ng build --configuration=production"

publish = "dist/league/browser"

[context.production.environment]
NODE_VERSION = "20.12.2"
NPM_VERSION = "8"
